CREATE TABLE IF NOT EXISTS UserApp (
Id SERIAL PRIMARY KEY NOT NULL,
Name VARCHAR(120) NOT NULL,
Email VARCHAR(120) NOT NULL,
IsEmailValidated BOOLEAN NOT NULL,
IsActive BOOLEAN NOT NULL,
Password VARCHAR(30) NOT NULL,
Level INT NOT NULL,
Exp SERIAL NOT NULL,
LevelMaxExp SERIAL NOT NULL,
ProfileImgUrl VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
Id SERIAL PRIMARY KEY NOT NULL,
GoogleBookId VARCHAR(120) NOT NULL,
UserId SERIAL NOT NULL,
Status INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES UserApp (Id)
);

CREATE TABLE IF NOT EXISTS UserLevel (
Id SERIAL PRIMARY KEY NOT NULL,
UserId SERIAL NOT NULL,
Level INT NOT NULL,
Exp SERIAL NOT NULL,
LevelMaxExp SERIAL NOT NULL,
FOREIGN KEY (UserId) REFERENCES UserApp (Id)
);

DROP TABLE Book;
DROP TABLE UserLevel;
DROP TABLE UserApp;