CREATE IF NOT EXISTS TABLE "user" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  is_email_validated BOOLEAN NOT NULL,
  is_active BOOLEAN NOT NULL,
  password VARCHAR(30) NOT NULL,
  profile_img_url VARCHAR(200) NOT NULL
);

CREATE TABLE book (
  id SERIAL PRIMARY KEY NOT NULL,
  google_book_id VARCHAR(120) NOT NULL,
  user_id SERIAL NOT NULL,
  status INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES "USER" (id)
);

CREATE TABLE user_level (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id SERIAL NOT NULL,
  level INT NOT NULL,
  exp SERIAL NOT NULL,
  level_max_exp SERIAL NOT NULL,
  FOREIGN KEY (user_id) REFERENCES "USER" (id) 
);

DROP TABLE book
DROP TABLE "USER"