CREATE TABLE "USER" (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  EMAIL VARCHAR(120) NOT NULL,
  IS_EMAIL_VALIDATED BOOLEAN NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  PROFILE_IMG_URL VARCHAR(200) NOT NULL
);

SELECT * FROM USER;